In [2]:
import math
import numpy as np
import cv2 as cv

In [3]:
QM = np.asarray([[16 ,11 ,10 ,16 ,24 ,40 ,51 ,61],
       [12 ,12 ,14 ,19 ,26 ,58 ,60 ,55],
       [14 ,13 ,16 ,24 ,40 ,57 ,69 ,56],
       [14 ,17 ,22 ,29 ,51 ,87 ,80 ,62],
       [18 ,22 ,37 ,56 ,68 ,109 ,103 ,77],
       [24 ,35 ,55 ,64 ,81 ,104 ,113 ,92],
       [49 ,64 ,78 ,87 ,103 ,121 ,120 ,101],
       [72 ,92 ,95 ,98 ,112 ,100 ,103 ,99]])

In [22]:
def dct_2d(block, QM = QM):
    N = block.shape[0]
    
    output = np.zeros(block.shape)
    print(block.shape)
    for i in range(N):
        for j in range(N):
            #caculate FDCT
            Sum = 0
            
            for k in range(N):
                for l in range(N):
                    Sum = Sum + ( block[k,l]*math.cos( ((2*k)+1)*(i*math.pi)/16)*math.cos( ((2*l)+1)*(j*math.pi)/16)) 
            Cu = math.sqrt(1/2) if i == 0 else 1
            Cv = math.sqrt(1/2) if j == 0 else 1
            Suv = (1/4)*Cu*Cv*Sum #output[i,j] be4 Quantazation
            #quantazation
            output[i,j] = (Suv//QM[i,j])
    return output
            

In [6]:
#4 testing-purpose
import random
def generate_RGB_img():
    test_img = np.zeros((16,16,3), dtype = 'int16')
    for i in range(3):
        for x in range(test_img[:,:,i].shape[0]):
            for y in range(test_img[:,:,i].shape[1]):
                test_img[x,y,i] = random.randint(0,255)
    return test_img
img = generate_RGB_img()

In [17]:
block = img[:8,:8,0]
# print(block)
block_centered = block - 128
print(block_centered) #block_centered

[[ -50  -22  -52  110    6 -116   27   70]
 [ -12   56   41   84   99   -7   34  -55]
 [  -5  -82   76   76 -101   43   76  -79]
 [ -82  -72  -65   49   22  -46  -86 -124]
 [   4   -9    9  -99  -64  -72 -118   77]
 [  75   48 -121   99  -32  114  -38   58]
 [  83  122  111  -43 -114   68  -95   36]
 [  78  101   21   27   43   71   34   30]]


In [23]:
output_block = dct_2d(block)
print(output_block) #Block after DCT and quantazation

(8, 8)
[[ 66.   6.  -2.  -3.   1.   0.   0.  -2.]
 [ -8.  -7. -11.  -4.   2.   2.  -3.   1.]
 [ 13.   0.   1.  -2.  -1.  -1.  -2.   0.]
 [ -2.  -2.   5.  -2.   2.  -2.  -1.  -2.]
 [ -7.  -3.   0.  -1.   1.  -1.  -1.   0.]
 [ -4.   0.  -1.  -1.  -1.   0.   0.  -1.]
 [  0.  -2.   0.   0.   0.   0.  -1.  -1.]
 [ -1.   0.   1.  -2.  -1.   0.   1.   0.]]
